name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: nix flake check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: determinatesystems/nix-installer-action@v16
      - uses: determinatesystems/magic-nix-cache-action@v9
      - run: nix flake check --all-systems
